<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'_' => ['block_b14a7', 'html'],
		'_outer' => ['blockOuter', 'html'],
		'_inner' => ['blockInner', 'html'],
		'_title' => ['blockTitle', 'html'],
		'_title2' => ['blockTitle2', 'html'],
	];


	function render()
	{
%A%
// prolog Nette\Bridges\ApplicationLatte\UIMacros
if (Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this)) return;

// main template
?>

<?php if ($this->tryRenderParent(get_defined_vars())) return ?>
<div id="<?php echo $_control->getSnippetId('') ?>"><?php call_user_func(reset($this->blockQueue['_']), $this->params) ?>
</div>


<div id="<?php echo $_control->getSnippetId('outer') ?>"><?php call_user_func(reset($this->blockQueue['_outer']), $this->params) ?>
</div>


	@<?php if (true) { ?> Hello World @<?php } ?>


	<h2 id="<?php echo $_control->getSnippetId('title') ?>"><?php call_user_func(reset($this->blockQueue['_title']), $this->params) ?>
</h2>
	<h2 id="<?php echo $_control->getSnippetId('title2') ?>"><?php call_user_func(reset($this->blockQueue['_title2']), $this->params) ?>
</h2><?php
	}


	function block_%h%($_args)
	{
		extract($_args);
$_control->redrawControl('', FALSE);


	}


	function blockOuter($_args)
	{
		extract($_args);
$_control->redrawControl('outer', FALSE)
?>	Outer
		<div id="<?php echo $_control->getSnippetId('inner') ?>"><?php call_user_func(reset($this->blockQueue['_inner']), $this->params) ?>
</div>	/Outer
<?php
	}


	function blockInner($_args)
	{
		extract($_args);
$_control->redrawControl('inner', FALSE)
?>Inner<?php
	}


	function blockTitle($_args)
	{
		extract($_args);
$_control->redrawControl('title', FALSE)
?>Title 1<?php
	}


	function blockTitle2($_args)
	{
		extract($_args);
$_control->redrawControl('title2', FALSE)
?>Title 2<?php
	}

}
