<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'_outer1' => ['blockOuter1', 'html'],
		'_outer2' => ['blockOuter2', 'html'],
	];


	function render()
	{
%A%
// prolog Nette\Bridges\ApplicationLatte\UIMacros
if (Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this)) return;

// main template
if ($this->tryRenderParent(get_defined_vars())) return ?>
<div id="<?php echo $_control->getSnippetId('outer1') ?>"><?php call_user_func(reset($this->blockQueue['_outer1']), $this->params) ?>
</div>

<div id="<?php echo $_control->getSnippetId('outer2') ?>"><?php call_user_func(reset($this->blockQueue['_outer2']), $this->params) ?>
</div><?php
	}


	function blockOuter1($_args)
	{
		extract($_args);
$_control->redrawControl('outer1', FALSE);

%a% foreach (array(1,2,3) as $id) { ?>
		<div<?php echo ' id="' . ($this->local->dynSnippetId = $_control->getSnippetId("inner-$id")) . '"' ?>>
<?php ob_start() ?>				#<?php echo LFilters::escapeHtmlText($id) ?>

<?php $this->local->dynSnippets[$this->local->dynSnippetId] = ob_get_flush() ?>		</div>
<?php $iterations++; } ?>
	<?php if (isset($this->local->dynSnippets)) return $this->local->dynSnippets;
	}


	function blockOuter2($_args)
	{
		extract($_args);
$_control->redrawControl('outer2', FALSE);

%a% foreach (array(1,2,3) as $id) { ?>
		<div<?php echo ' id="' . ($this->local->dynSnippetId = $_control->getSnippetId("inner-$id")) . '"' ?>>
<?php ob_start() ?>				#<?php echo LFilters::escapeHtmlText($id) ?>

<?php $this->local->dynSnippets[$this->local->dynSnippetId] = ob_get_flush() ?>		</div>
<?php $iterations++; } ?>
	<?php if (isset($this->local->dynSnippets)) return $this->local->dynSnippets;
	}

}
