%A%
// block _
//
if (!function_exists($_b->blocks['_'][] = '_%[a-z0-9]+%__')) { function _%[a-z0-9]+%__($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl(%[false']+%, FALSE)
;
}}

//
// block _outer
//
if (!function_exists($_b->blocks['_outer'][] = '_%[a-z0-9]+%__outer')) { function _%[a-z0-9]+%__outer($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('outer', FALSE)
?>	Outer
		<div id="<?php echo $_control->getSnippetId('inner') ?>"><?php call_user_func(reset($_b->blocks['_inner']), $_b, $template->getParameters()) ?>
</div>
	/Outer
<?php
}}

//
// block _inner
//
if (!function_exists($_b->blocks['_inner'][] = '_%[a-z0-9]+%__inner')) { function _%[a-z0-9]+%__inner($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('inner', FALSE)
?>Inner<?php
}}

//
// block _title
//
if (!function_exists($_b->blocks['_title'][] = '_%[a-z0-9]+%__title')) { function _%[a-z0-9]+%__title($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('title', FALSE)
?>Title 1<?php
}}

//
// block _title2
//
if (!function_exists($_b->blocks['_title2'][] = '_%[a-z0-9]+%__title2')) { function _%[a-z0-9]+%__title2($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('title2', FALSE)
?>Title 2<?php
}}

//
// end of blocks
%A%
	return Nette\Bridges\ApplicationLatte\UIMacros::renderSnippets($_control, $_b, get_defined_vars());
%A%
<div id="<?php echo $_control->getSnippetId('') ?>"><?php call_user_func(reset($_b->blocks['_']), $_b, $template->getParameters()) ?>
</div>


<div id="<?php echo $_control->getSnippetId('outer') ?>"><?php call_user_func(reset($_b->blocks['_outer']), $_b, $template->getParameters()) ?>
</div>


	@<?php if (true) { ?> Hello World @<?php } ?>


	<h2 id="<?php echo $_control->getSnippetId('title') ?>"><?php call_user_func(reset($_b->blocks['_title']), $_b, $template->getParameters()) ?>
</h2>

	<h2 id="<?php echo $_control->getSnippetId('title2') ?>"><?php call_user_func(reset($_b->blocks['_title2']), $_b, $template->getParameters()) ?>
</h2>
<?php
%A%
