<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'_outer' => 'blockOuter',
	];

	public $blockTypes = [
		'_outer' => 'html',
	];


	function render()
	{
%A%
		// prolog Nette\Bridges\ApplicationLatte\UIMacros
		if (Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this, $this->blockQueue)) return;

		// main template
		?><div id="<?php echo $_control->getSnippetId('outer') ?>"><?php call_user_func(reset($this->blockQueue['_outer']), $this->params) ?></div><?php

	}


	function prepare()
	{
		extract($this->params);
		$this->parentName = $this->parentName ?: ($this->blocks && !$this->getReferringTemplate() && $this->params["_control"] instanceof Nette\Application\UI\Presenter
		? $this->params["_control"]->findLayoutTemplateFile() : NULL);
		return get_defined_vars();
	}


	function blockOuter($_args)
	{
		extract($_args);
		$_control->redrawControl('outer', FALSE);

		$iterations = 0;
		%a%
		foreach (array(1,2,3) as $id) {
			?>		<div id="<?php echo $this->local->dynSnippetId = $_control->getSnippetId("inner-$id") ?>"><?php ob_start() ?>

				#<?php echo LFilters::escapeHtml($id) ?>

<?php $this->local->dynSnippets[$this->local->dynSnippetId] = ob_get_flush() ?></div><?php
			$iterations++;
		}
		?>	<?php
		if (isset($this->local->dynSnippets)) return $this->local->dynSnippets;

	}

}
