<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'_outer' => ['blockOuter', 'html'],
		'_inner' => ['blockInner', 'html'],
		'_gallery' => ['blockGallery', 'html'],
	];


	function render()
	{
%A%
// prolog Nette\Bridges\ApplicationLatte\UIMacros

// snippets support
if (empty($this->local->parentName) && !empty($_control->snippetMode) && empty($_g->includingBlock)) {
	return Nette\Bridges\ApplicationLatte\UIRuntime::renderSnippets($_control, $_b, get_defined_vars());
}

// main template
?>	<div class="test"<?php echo ' id="' . $_control->getSnippetId('outer') . '"' ?>>
<?php if ($this->tryRenderParent(get_defined_vars())) return;call_user_func(reset($this->blockQueue['_outer']), $this->params) ?>
	</div>

	<div class="test"<?php echo ' id="' . $_control->getSnippetId('inner') . '"' ?>>
<?php call_user_func(reset($this->blockQueue['_inner']), $this->params)  ?>	</div>

	<div class="<?php echo LFilters::escapeHtmlAttr('class') ?>"<?php echo ' id="' . $_control->getSnippetId('gallery') . '"' ?>
><?php call_user_func(reset($this->blockQueue['_gallery']), $this->params) ?>
</div>
<?php
	}


	function blockOuter($_args)
	{
		extract($_args);
$_control->redrawControl('outer', FALSE)
?>	<p>Outer</p>
<?php
	}


	function blockInner($_args)
	{
		extract($_args);
$_control->redrawControl('inner', FALSE)
?>	<p>Inner</p>
<?php
	}


	function blockGallery($_args)
	{
		extract($_args);
$_control->redrawControl('gallery', FALSE);


	}

}
