<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'_outer' => 'blockOuter',
		'_inner' => 'blockInner',
		'_gallery' => 'blockGallery',
	];

	public $blockTypes = [
		'_outer' => 'html',
		'_inner' => 'html',
		'_gallery' => 'html',
	];


	function render()
	{
%A%
		// prolog Nette\Bridges\ApplicationLatte\UIMacros
		if (Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this, $this->blockQueue)) return;

		// main template
		?>	<div class="test"<?php echo ' id="' . $_control->getSnippetId('outer') . '"' ?>>
<?php call_user_func(reset($this->blockQueue['_outer']), $this->params) ?>
	</div>

	<div class="test"<?php echo ' id="' . $_control->getSnippetId('inner') . '"' ?>>
<?php
		call_user_func(reset($this->blockQueue['_inner']), $this->params);
		?>	</div>

	<div class="<?php echo LFilters::escapeHtmlAttr('class') ?>"<?php echo ' id="' . $_control->getSnippetId('gallery') . '"' ?>><?php
		call_user_func(reset($this->blockQueue['_gallery']), $this->params) ?>
</div>
<?php

	}


	function prepare()
	{
		extract($this->params);
		$this->parentName = $this->parentName ?: ($this->blocks && !$this->getReferringTemplate() && $this->params["_control"] instanceof Nette\Application\UI\Presenter
		? $this->params["_control"]->findLayoutTemplateFile() : NULL);
		return get_defined_vars();
	}


	function blockOuter($_args)
	{
		extract($_args);
		$_control->redrawControl('outer', FALSE);

		?>	<p>Outer</p>
<?php
	}


	function blockInner($_args)
	{
		extract($_args);
		$_control->redrawControl('inner', FALSE);

		?>	<p>Inner</p>
<?php
	}


	function blockGallery($_args)
	{
		extract($_args);
		$_control->redrawControl('gallery', FALSE);


	}

}
