<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'_outer1' => 'blockOuter1',
		'_outer2' => 'blockOuter2',
	];

	public $blockTypes = [
		'_outer1' => 'html',
		'_outer2' => 'html',
	];


	function render()
	{
%A%
		// prolog Nette\Bridges\ApplicationLatte\UIMacros
		if (Nette\Bridges\ApplicationLatte\UIRuntime::initialize($this, $this->blockQueue)) return;

		// main template
		?><div id="<?php echo $this->global->uiControl->getSnippetId('outer1') ?>"><?php call_user_func(reset($this->blockQueue['_outer1']), $this->params) ?></div>

<div id="<?php echo $this->global->uiControl->getSnippetId('outer2') ?>"><?php call_user_func(reset($this->blockQueue['_outer2']), $this->params) ?></div><?php

	}


	function prepare()
	{
		extract($this->params);
		$this->parentName = $this->parentName ?: ($this->blocks && !$this->getReferringTemplate()
		&& isset($this->global->uiControl) && $this->global->uiControl instanceof Nette\Application\UI\Presenter
		? $this->global->uiControl->findLayoutTemplateFile() : NULL);
		return get_defined_vars();
	}


	function blockOuter1($_args)
	{
		extract($_args);
		$this->global->uiControl->redrawControl('outer1', FALSE);

		$iterations = 0;
		foreach (array(1,2,3) as $id) {
			?>		<div<?php echo ' id="' . ($this->global->dynSnippetId = $this->global->uiControl->getSnippetId("inner-$id")) . '"' ?>>
<?php
			ob_start();
			?>				#<?php echo LR\Filters::escapeHtml($id) /* line 4 */ ?>

<?php
			$this->global->dynSnippets[$this->global->dynSnippetId] = ob_get_flush();
?>		</div>
<?php
			$iterations++;
		}
		?>	<?php
		if (isset($this->global->dynSnippets)) return $this->global->dynSnippets;

	}


	function blockOuter2($_args)
	{
		extract($_args);
		$this->global->uiControl->redrawControl('outer2', FALSE);

		$iterations = 0;
		foreach (array(1,2,3) as $id) {
			?>		<div<?php echo ' id="' . ($this->global->dynSnippetId = $this->global->uiControl->getSnippetId("inner-$id")) . '"' ?>>
<?php
			ob_start();
			?>				#<?php echo LR\Filters::escapeHtml($id) /* line 13 */ ?>

<?php
			$this->global->dynSnippets[$this->global->dynSnippetId] = ob_get_flush();
?>		</div>
<?php
			$iterations++;
		}
		?>	<?php
		if (isset($this->global->dynSnippets)) return $this->global->dynSnippets;

	}

}
