<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'block1' => 'blockBlock1',
		'_snippet' => 'blockSnippet',
		'_outer' => 'blockOuter',
		'block2' => 'blockBlock2',
	];

	public $blockTypes = [
		'block1' => 'html',
		'_snippet' => 'html',
		'_outer' => 'html',
		'block2' => 'html',
	];


	function render()
	{
%A%
		// main template
		call_user_func(reset($this->blockQueue['block1']), get_defined_vars());
		?>


<div id="<?php echo $_control->getSnippetId('outer') ?>"><?php call_user_func(reset($this->blockQueue['_outer']), $this->params) ?></div><?php

	}


	function blockBlock1($_args)
	{
		extract($_args);
		?><div<?php echo ' id="' . $_control->getSnippetId('snippet') . '"' ?>>
<?php call_user_func(reset($this->blockQueue['_snippet']), $this->params) ?>
</div>
<?php

	}


	function blockSnippet($_args)
	{
		extract($_args);
		$_control->redrawControl('snippet', FALSE);

		?>		static
<?php
	}


	function blockOuter($_args)
	{
		extract($_args);
		$_control->redrawControl('outer', FALSE);

		?>
begin
<?php
		call_user_func(reset($this->blockQueue['block2']), get_defined_vars());
		?>
end
<?php
		if (isset($this->local->dynSnippets)) return $this->local->dynSnippets;

	}


	function blockBlock2($_args)
	{
		extract($_args);
		?><div<?php echo ' id="' . ($this->local->dynSnippetId = $_control->getSnippetId("inner-$id")) . '"' ?>>
<?php ob_start() ?>		dynamic
<?php $this->local->dynSnippets[$this->local->dynSnippetId] = ob_get_flush() ?></div>
<?php

	}

}
