<?php
// source: %a%
%A%
// prolog Latte\Macros\BlockMacros
//
// block _outer1
//
if (!function_exists($_b->blocks['_outer1'][] = '_%[a-z0-9]+%__outer1')) { function _%[a-z0-9]+%__outer1($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('outer1', FALSE)
;%a% foreach (array(1,2,3) as $id) { ?>
		<div<?php echo ' id="' . ($_l->dynSnippetId = $_control->getSnippetId("inner-$id")) . '"' ?>>
<?php ob_start() ?>				#<?php echo Latte\Runtime\Filters::escapeHtml($id, ENT_NOQUOTES) ?>

<?php $_l->dynSnippets[$_l->dynSnippetId] = ob_get_flush() ?>		</div>
<?php $iterations++; } ?>
	<?php if (isset($_l->dynSnippets)) return $_l->dynSnippets;
}}

//
// block _outer2
//
if (!function_exists($_b->blocks['_outer2'][] = '_%[a-z0-9]+%__outer2')) { function _%[a-z0-9]+%__outer2($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v; $_control->redrawControl('outer2', FALSE)
;%a% foreach (array(1,2,3) as $id) { ?>
		<div<?php echo ' id="' . ($_l->dynSnippetId = $_control->getSnippetId("inner-$id")) . '"' ?>>
<?php ob_start() ?>				#<?php echo Latte\Runtime\Filters::escapeHtml($id, ENT_NOQUOTES) ?>

<?php $_l->dynSnippets[$_l->dynSnippetId] = ob_get_flush() ?>		</div>
<?php $iterations++; } ?>
	<?php if (isset($_l->dynSnippets)) return $_l->dynSnippets;
}}

//
// end of blocks
//

// template extending

$_l->extends = empty($_g->extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $_g->extended = TRUE;

if ($_l->extends) { ob_start();}

// prolog Nette\Bridges\ApplicationLatte\UIMacros

// snippets support
if (empty($_l->extends) && !empty($_control->snippetMode)) {
	return Nette\Bridges\ApplicationLatte\UIRuntime::renderSnippets($_control, $_b, get_defined_vars());
}

//
// main template
//
if ($_l->extends) { ob_end_clean(); return $template->renderChildTemplate($_l->extends, get_defined_vars()); } ?>
<div id="<?php echo $_control->getSnippetId('outer1') ?>"><?php call_user_func(reset($_b->blocks['_outer1']), $_b, $template->getParameters()) ?>
</div>

<div id="<?php echo $_control->getSnippetId('outer2') ?>"><?php call_user_func(reset($_b->blocks['_outer2']), $_b, $template->getParameters()) ?>
</div><?php
%A%
