language: php
php:
    - 7.1

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

matrix:
    include:
        - php: 7.1
          env: dependencies="--prefer-lowest --prefer-stable" PHP_BIN=php
        - php: 7.1
          env: coverage=on

    allow_failures:
        - php: 7.1
          env: coverage=on

script:
    - vendor/bin/tester -p $PHP_BIN tests -s $coverageArgs
    - php temp/code-checker/src/code-checker.php --short-arrays --strict-types
    # Run Coding Standard
    - temp/nette-coding-standard/vendor/symplify/easy-coding-standard/bin/ecs check src tests --configuration temp/nette-coding-standard/easy-coding-standard.neon

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer update --no-interaction --prefer-dist $dependencies
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.8 --no-interaction
    - if [ "$coverage" == "on" ]; then PHP_BIN=phpdbg; coverageArgs="--coverage ./coverage.xml --coverage-src ./src"; fi
    # Install Coding Standard
    - travis_retry composer create-project nette/coding-standard temp/nette-coding-standard -s dev
    # todo: add symplify/easy-coding-standard

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
