<?php

/**
 * Default error page.
 * @param  int  $code
 */

declare(strict_types=1);

namespace NetteModule;

$messages = [
	0 => ['Oops...', 'Your browser sent a request that this server could not understand or process.'],
	403 => ['Access Denied', 'You do not have permission to view this page. Please try contact the web site administrator if you believe you should be able to view this page.'],
	404 => ['Page Not Found', 'The page you requested could not be found. It is possible that the address is incorrect, or that the page no longer exists. Please use a search engine to find what you are looking for.'],
	405 => ['Method Not Allowed', 'The requested method is not allowed for the URL.'],
	410 => ['Page Not Found', 'The page you requested has been taken off the site. We apologize for the inconvenience.'],
	500 => ['Server Error', 'We\'re sorry! The server encountered an internal error and was unable to complete your request. Please try again later.'],
];
$message = $messages[$code] ?? $messages[0];

?>
<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name=robots content=noindex>
<meta name=generator content="Nette Framework">
<title><?= $message[0] ?></title>

<style>
	#nette-error { all: initial; position: absolute; top: 0; left: 0; right: 0; height: 70vh; min-height: 400px; display: flex; align-items: center; justify-content: center; z-index: 1000 }
	#nette-error div { all: initial; max-width: 550px; background: white; color: #333; display: block }
	#nette-error h1 { all: initial; font: bold 50px/1.1 sans-serif; display: block; margin: 40px }
	#nette-error p { all: initial; font: 20px/1.4 sans-serif; margin: 40px; display: block }
	#nette-error small { color: gray }
</style>

<div id=nette-error>
	<div>
		<h1><?= $message[0] ?></h1>

		<p><?= $message[1] ?></p>

		<?php if ($code): ?><p><small>error <?= $code ?></small></p><?php endif ?>
	</div>
</div>

<script>
	document.body.insertBefore(document.getElementById('nette-error'), document.body.firstChild);
</script>
